#services:
#  http:
#    image: nginx:latest
#    ports:
#      - 8080:80
#    volumes:
#      - ./html:/usr/share/nginx/html:ro

services:
  mysqldb:
    image: mysql:8.0.41
    ports:
      - '3306:3306'
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

#  postgresdb:
#    image: postgres:latest
#    ports:
#      - '5432:5432'
#    environment:
#      - POSTGRES_DB=app
#      - POSTGRES_USER=app
#      - POSTGRES_PASSWORD=pass